- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
      homebrew_taps: 
        - Homebrew/homebrew-core
        - caskroom/homebrew-cask
      homebrew_packages: 
        - { name: ag }
        - { name: autoconf }
        - { name: awscli }
        - { name: awslogs }
        - { name: bash }
        - { name: bash-completion }
        - { name: cert }
        - { name: cocot }
        - { name: colordiff }
        - { name: coreutils }
        - { name: direnv }
        - { name: ghq }
        - { name: git }
        - { name: git-now }
        - { name: git-secrets }
        - { name: go }
        - { name: goenv }
        - { name: htop }
        - { name: httpstat }
        - { name: iproute2mac }
        - { name: jq }
        - { name: libevent }
        - { name: libwebsockets}
        - { name: libyaml}
        - { name: lua }
        - { name: luajit }
        - { name: mosquitto }
        - { name: mysql}
        - { name: nkf }
        - { name: nmap }
        - { name: node }
        - { name: node-build }
        - { name: npm }
        - { name: nodenv }
        - { name: oniguruma }
        - { name: openssl, state: linked, install_options: force }
        - { name: ossp-uuid }
        - { name: pcre }
        - { name: peco }
        - { name: perl }
        - { name: perl-build }
        - { name: plenv }
        - { name: pkg-config }
        - { name: pv }
        - { name: pwgen }
        - { name: pyenv }
        - { name: rbenv }
        - { name: readline }
        - { name: reattach-to-user-namespace }
        - { name: rmtrash }
        - { name: rbenv }
        - { name: ruby-build }
        - { name: sqlite }
        - { name: telnet}
        - { name: terraform }
        - { name: tfenv }
        - { name: the_silver_searcher}
        - { name: tmux }
        - { name: tree }
        - { name: coreutils }
        - { name: vegeta }
        - { name: vim }
        - { name: watch }
        - { name: wget }
        - { name: yarn}
        - { name: zsh }

      homebrew_cask_packages:
        - name: clipy 
        - name: docker-toolbox
        - name: vagrant
        - name: google-chrome
        - name: karabiner-elements
        - name: iterm2
        - name: slack
        - name: marp
        - name: firefox
        - name: scroll-reverser
        - name: skitch
        - name: lastpass

  tasks:
      - name: "add repository"
        homebrew_tap:
            name: "{{ item }}"
            state: present
        with_items: "{{ homebrew_taps }}"

      - name: update homebrew
        homebrew:
            update_homebrew: yes

      - name: "install package"
        homebrew:
            name: "{{ item.name}}"
            state: "{{ item.state | default('latest') }}"
            install_options: "{{ item.install_options | default(omit) }}"
        with_items: "{{ homebrew_packages }}"
        register: brew_result
      
      - debug: var=result

      - name: "install cask package"
        homebrew_cask:
            name: "{{ item.name}}"
            state: "{{ item.state | default('present') }}"
        with_items: "{{ homebrew_cask_packages }}"

      - debug: var=result

      - name: "make brew info dir"
        file:
            path: brew_info
            state: directory

      - name: "save brew info"
        shell: "brew info {{ item }} > brew_info/{{ item }}"
        with_items: "{{ brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list }}"
